# Generated by Django 2.2.7 on 2019-11-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20191121_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='username',
        ),
    ]
