# Generated by Django 2.2.7 on 2019-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20191118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
